---
- name: Remove all apps from Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    type: array
    value: []

- name: Hide the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: Make the Dock the smallest size possible
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 32

- name: Restart the Dock to apply changes
  shell: killall Dock || true
  ignore_errors: true
