---
- name: Check if wallpaper exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/wallpapers/{{ wallpaper_file }}"
  register: wallpaper_sourced

- name: Set desktop wallpaper
  command: osascript -e 'tell application "System Events" to set picture of desktop 1 to "{{ wallpaper_sourced.stat.path }}"'
  when: wallpaper_sourced.stat.exists
  changed_when: true


- name: Enable Dark Mode using defaults
  osx_defaults:
    domain: Apple Global Domain
    key: AppleInterfaceStyle
    value: Dark
    type: string

- name: Check if AeroSpace.app exists
  ansible.builtin.stat:
    path: "/Applications/AeroSpace.app"
  register: aerospace_check

- name: Start AeroSpace.app
  ansible.builtin.command: open -a AeroSpace
  when: aerospace_check.stat.exists
  changed_when: false
